version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_DB_ROOT_USERNAME: "${MONGO_DB_ROOT_USERNAME}"
      MONGO_DB_ROOT_PASSWORD: "${MONGO_DB_ROOT_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@mongo:27017/todos?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
